Updated most ERROR strings
PORTS: Now mentions the ports as only one of the possible causes of the error.
EXCEPTION: Added information about the app being restarted.
LAUNCH_DATA_INVALID: Now asks for launching any server, not a specific one.